from turtle import *

bgcolor('black')
speed(0)
hideturtle()
for i in range(280):
    color('red')
    circle(i)
    color('red')
    circle(i*0.8)
    color('orange')
    circle(i*0.6)
    color('yellow')
    circle(i*0.7)
    color('white')
    circle(i*0.5)
    color('purple')
    circle(i*0.9)
    color('white')
    circle(i*0.95)
    right(20)
    left(15)
    forward(2)
done()
