word1 = input("Enter a phrase or a word that relates to what can happen to a person while walking: ")
word2 = input("Enter a creature or any living being: ")
word3 = input("Enter something related to escape: ")
print ("A person was walking " + word1)
print ("He met " + word2)
print ("He was very sacred of " + word2)
print ("He overcame his fear of " + word2 + " and asked how to get out of there.\nBut the " + word2 + " said that there is a " + word3)
print ("Like this The person and " + word2 + "became friends. They shared ")
print ("And now they lived happily ever after.")
print ("This is the end of this mad libs game.")
print ("I am aware that it is terrible.")
